"""Add time_blocks table

Revision ID: 3186aff70964
Revises: 
Create Date: 2024-12-12 09:45:05.483419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3186aff70964'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hour_id', sa.Integer(), nullable=True),
    sa.Column('week_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_blocks_day'), 'time_blocks', ['day'], unique=False)
    op.create_index(op.f('ix_time_blocks_hour_id'), 'time_blocks', ['hour_id'], unique=False)
    op.create_index(op.f('ix_time_blocks_id'), 'time_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_time_blocks_week_id'), 'time_blocks', ['week_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_blocks_week_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_hour_id'), table_name='time_blocks')
    op.drop_index(op.f('ix_time_blocks_day'), table_name='time_blocks')
    op.drop_table('time_blocks')
    # ### end Alembic commands ###
