"""Add ClassTime model and relationships

Revision ID: 66c2be46210d
Revises: b355b49bf2fa
Create Date: 2025-02-02 14:03:54.381239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c2be46210d'
down_revision: Union[str, None] = 'b355b49bf2fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
