"""fix ClassTime model and relationships

Revision ID: 6efb885142c4
Revises: 66c2be46210d
Create Date: 2025-02-02 14:12:53.797252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efb885142c4'
down_revision: Union[str, None] = '66c2be46210d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_room_id', sa.Integer(), nullable=True),
    sa.Column('time_block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_room_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['time_block_id'], ['time_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_time_class_room_id'), 'class_time', ['class_room_id'], unique=False)
    op.create_index(op.f('ix_class_time_id'), 'class_time', ['id'], unique=False)
    op.create_index(op.f('ix_class_time_time_block_id'), 'class_time', ['time_block_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_time_time_block_id'), table_name='class_time')
    op.drop_index(op.f('ix_class_time_id'), table_name='class_time')
    op.drop_index(op.f('ix_class_time_class_room_id'), table_name='class_time')
    op.drop_table('class_time')
    # ### end Alembic commands ###
