"""Add CareerTeacher model

Revision ID: b355b49bf2fa
Revises: ad20255a4062
Create Date: 2025-01-31 22:00:45.555943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b355b49bf2fa'
down_revision: Union[str, None] = 'ad20255a4062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_teacher_career_id'), 'career_teacher', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_teacher_id'), 'career_teacher', ['id'], unique=False)
    op.create_index(op.f('ix_career_teacher_teacher_id'), 'career_teacher', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_teacher_teacher_id'), table_name='career_teacher')
    op.drop_index(op.f('ix_career_teacher_id'), table_name='career_teacher')
    op.drop_index(op.f('ix_career_teacher_career_id'), table_name='career_teacher')
    op.drop_table('career_teacher')
    # ### end Alembic commands ###
